<?php

use Carbon\Carbon;
use Webpatser\Uuid\Uuid;
use App\Models\Location\City;
use Illuminate\Database\Seeder;
use App\Models\Location\Country;
use App\Models\Location\Province;

class LocationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::select('SET FOREIGN_KEY_CHECKS=0;');
        City::truncate();
        Province::truncate();
        Country::truncate();
        DB::select('SET FOREIGN_KEY_CHECKS=1;');
        try {
            DB::select('ALTER TABLE master_provinces DROP COLUMN old_id');
            DB::select('ALTER TABLE master_cities DROP COLUMN province_old_id');
        } catch(Exception $e) {

        }

        $countryId = Uuid::generate()->string;
        Country::insert([
            ['id' => $countryId, 'name' => 'Indonesia', 'created_at' => now(), 'updated_at' => now()]
        ]);

        DB::select('ALTER TABLE master_provinces ADD COLUMN old_id INT(10) UNSIGNED');
        DB::select('ALTER TABLE master_cities ADD COLUMN province_old_id INT(10) UNSIGNED');
        Province::insert([
            ['id' => Uuid::generate()->string, 'old_id' => '11', 'name' => 'Aceh', 'country_id' => $countryId, 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'old_id' => '12', 'name' => 'Sumatera Utara', 'country_id' => $countryId, 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'old_id' => '13', 'name' => 'Sumatera Barat', 'country_id' => $countryId, 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'old_id' => '14', 'name' => 'Riau', 'country_id' => $countryId, 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'old_id' => '15', 'name' => 'Jambi', 'country_id' => $countryId, 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'old_id' => '16', 'name' => 'Sumatera Selatan', 'country_id' => $countryId, 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'old_id' => '17', 'name' => 'Bengkulu', 'country_id' => $countryId, 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'old_id' => '18', 'name' => 'Lampung', 'country_id' => $countryId, 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'old_id' => '19', 'name' => 'Kepulauan Bangka Belitung', 'country_id' => $countryId, 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'old_id' => '21', 'name' => 'Kepulauan Riau', 'country_id' => $countryId, 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'old_id' => '31', 'name' => 'Dki Jakarta', 'country_id' => $countryId, 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'old_id' => '32', 'name' => 'Jawa Barat', 'country_id' => $countryId, 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'old_id' => '33', 'name' => 'Jawa Tengah', 'country_id' => $countryId, 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'old_id' => '34', 'name' => 'Di Yogyakarta', 'country_id' => $countryId, 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'old_id' => '35', 'name' => 'Jawa Timur', 'country_id' => $countryId, 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'old_id' => '36', 'name' => 'Banten', 'country_id' => $countryId, 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'old_id' => '51', 'name' => 'Bali', 'country_id' => $countryId, 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'old_id' => '52', 'name' => 'Nusa Tenggara Barat', 'country_id' => $countryId, 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'old_id' => '53', 'name' => 'Nusa Tenggara Timur', 'country_id' => $countryId, 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'old_id' => '61', 'name' => 'Kalimantan Barat', 'country_id' => $countryId, 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'old_id' => '62', 'name' => 'Kalimantan Tengah', 'country_id' => $countryId, 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'old_id' => '63', 'name' => 'Kalimantan Selatan', 'country_id' => $countryId, 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'old_id' => '64', 'name' => 'Kalimantan Timur', 'country_id' => $countryId, 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'old_id' => '65', 'name' => 'Kalimantan Utara', 'country_id' => $countryId, 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'old_id' => '71', 'name' => 'Sulawesi Utara', 'country_id' => $countryId, 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'old_id' => '72', 'name' => 'Sulawesi Tengah', 'country_id' => $countryId, 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'old_id' => '73', 'name' => 'Sulawesi Selatan', 'country_id' => $countryId, 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'old_id' => '74', 'name' => 'Sulawesi Tenggara', 'country_id' => $countryId, 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'old_id' => '75', 'name' => 'Gorontalo', 'country_id' => $countryId, 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'old_id' => '76', 'name' => 'Sulawesi Barat', 'country_id' => $countryId, 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'old_id' => '81', 'name' => 'Maluku', 'country_id' => $countryId, 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'old_id' => '82', 'name' => 'Maluku Utara', 'country_id' => $countryId, 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'old_id' => '91', 'name' => 'Papua Barat', 'country_id' => $countryId, 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'old_id' => '94', 'name' => 'Papua', 'country_id' => $countryId, 'created_at' => now(), 'updated_at' => now()]
        ]);

        $dummyProvinceId = Province::first()->id;
        City::insert([
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 11, 'name' => 'Simeulue', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 11, 'name' => 'Aceh Singkil', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 11, 'name' => 'Aceh Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 11, 'name' => 'Aceh Tenggara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 11, 'name' => 'Aceh Timur', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 11, 'name' => 'Aceh Tengah', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 11, 'name' => 'Aceh Barat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 11, 'name' => 'Aceh Besar', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 11, 'name' => 'Pidie', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 11, 'name' => 'Bireuen', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 11, 'name' => 'Aceh Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 11, 'name' => 'Aceh Barat Daya', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 11, 'name' => 'Gayo Lues', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 11, 'name' => 'Aceh Tamiang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 11, 'name' => 'Nagan Raya', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 11, 'name' => 'Aceh Jaya', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 11, 'name' => 'Bener Meriah', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 11, 'name' => 'Pidie Jaya', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 11, 'name' => 'Banda Aceh', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 11, 'name' => 'Sabang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 11, 'name' => 'Langsa', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 11, 'name' => 'Lhokseumawe', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 11, 'name' => 'Subulussalam', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 12, 'name' => 'Nias', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 12, 'name' => 'Mandailing Natal', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 12, 'name' => 'Tapanuli Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 12, 'name' => 'Tapanuli Tengah', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 12, 'name' => 'Tapanuli Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 12, 'name' => 'Toba Samosir', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 12, 'name' => 'Labuhan Batu', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 12, 'name' => 'Asahan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 12, 'name' => 'Simalungun', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 12, 'name' => 'Dairi', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 12, 'name' => 'Karo', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 12, 'name' => 'Deli Serdang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 12, 'name' => 'Langkat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 12, 'name' => 'Nias Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 12, 'name' => 'Humbang Hasundutan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 12, 'name' => 'Pakpak Bharat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 12, 'name' => 'Samosir', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 12, 'name' => 'Serdang Bedagai', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 12, 'name' => 'Batu Bara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 12, 'name' => 'Padang Lawas Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 12, 'name' => 'Padang Lawas', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 12, 'name' => 'Labuhan Batu Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 12, 'name' => 'Labuhan Batu Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 12, 'name' => 'Nias Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 12, 'name' => 'Nias Barat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 12, 'name' => 'Sibolga', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 12, 'name' => 'Tanjung Balai', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 12, 'name' => 'Pematang Siantar', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 12, 'name' => 'Tebing Tinggi', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 12, 'name' => 'Medan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 12, 'name' => 'Binjai', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 12, 'name' => 'Padang Sidempuan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 12, 'name' => 'Gunungsitoli', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 13, 'name' => 'Kepulauan Mentawai', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 13, 'name' => 'Pesisir Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 13, 'name' => 'Solok', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 13, 'name' => 'Sijunjung', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 13, 'name' => 'Tanah Datar', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 13, 'name' => 'Padang Pariaman', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 13, 'name' => 'Agam', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 13, 'name' => 'Lima Puluh Kota', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 13, 'name' => 'Pasaman', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 13, 'name' => 'Solok Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 13, 'name' => 'Dharmasraya', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 13, 'name' => 'Pasaman Barat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 13, 'name' => 'Padang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 13, 'name' => 'Solok', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 13, 'name' => 'Sawah Lunto', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 13, 'name' => 'Padang Panjang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 13, 'name' => 'Bukittinggi', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 13, 'name' => 'Payakumbuh', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 13, 'name' => 'Pariaman', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 14, 'name' => 'Kuantan Singingi', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 14, 'name' => 'Indragiri Hulu', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 14, 'name' => 'Indragiri Hilir', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 14, 'name' => 'Pelalawan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 14, 'name' => 'Siak', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 14, 'name' => 'Kampar', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 14, 'name' => 'Rokan Hulu', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 14, 'name' => 'Bengkalis', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 14, 'name' => 'Rokan Hilir', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 14, 'name' => 'Kepulauan Meranti', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 14, 'name' => 'Pekanbaru', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 14, 'name' => 'Dumai', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 15, 'name' => 'Kerinci', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 15, 'name' => 'Merangin', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 15, 'name' => 'Sarolangun', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 15, 'name' => 'Batang Hari', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 15, 'name' => 'Muaro Jambi', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 15, 'name' => 'Tanjung Jabung Timur', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 15, 'name' => 'Tanjung Jabung Barat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 15, 'name' => 'Tebo', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 15, 'name' => 'Bungo', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 15, 'name' => 'Jambi', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 15, 'name' => 'Sungai Penuh', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 16, 'name' => 'Ogan Komering Ulu', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 16, 'name' => 'Ogan Komering Ilir', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 16, 'name' => 'Muara Enim', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 16, 'name' => 'Lahat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 16, 'name' => 'Musi Rawas', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 16, 'name' => 'Musi Banyuasin', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 16, 'name' => 'Banyu Asin', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 16, 'name' => 'Ogan Komering Ulu Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 16, 'name' => 'Ogan Komering Ulu Timur', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 16, 'name' => 'Ogan Ilir', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 16, 'name' => 'Empat Lawang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 16, 'name' => 'Penukal Abab Lematang Ilir', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 16, 'name' => 'Musi Rawas Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 16, 'name' => 'Palembang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 16, 'name' => 'Prabumulih', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 16, 'name' => 'Pagar Alam', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 16, 'name' => 'Lubuk Linggau', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 17, 'name' => 'Bengkulu Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 17, 'name' => 'Rejang Lebong', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 17, 'name' => 'Bengkulu Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 17, 'name' => 'Kaur', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 17, 'name' => 'Seluma', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 17, 'name' => 'Muko Muko', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 17, 'name' => 'Lebong', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 17, 'name' => 'Kepahiang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 17, 'name' => 'Bengkulu Tengah', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 17, 'name' => 'Bengkulu', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 18, 'name' => 'Lampung Barat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 18, 'name' => 'Tanggamus', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 18, 'name' => 'Lampung Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 18, 'name' => 'Lampung Timur', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 18, 'name' => 'Lampung Tengah', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 18, 'name' => 'Lampung Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 18, 'name' => 'Way Kanan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 18, 'name' => 'Tulang Bawang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 18, 'name' => 'Pesawaran', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 18, 'name' => 'Pringsewu', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 18, 'name' => 'Mesuji', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 18, 'name' => 'Tulang Bawang Barat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 18, 'name' => 'Pesisir Barat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 18, 'name' => 'Bandar Lampung', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 18, 'name' => 'Metro', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 19, 'name' => 'Bangka', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 19, 'name' => 'Belitung', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 19, 'name' => 'Bangka Barat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 19, 'name' => 'Bangka Tengah', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 19, 'name' => 'Bangka Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 19, 'name' => 'Belitung Timur', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 19, 'name' => 'Pangkal Pinang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 21, 'name' => 'Karimun', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 21, 'name' => 'Bintan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 21, 'name' => 'Natuna', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 21, 'name' => 'Lingga', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 21, 'name' => 'Kepulauan Anambas', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 21, 'name' => 'Batam', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 21, 'name' => 'Tanjung Pinang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 31, 'name' => 'Kepulauan Seribu', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 31, 'name' => 'Jakarta Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 31, 'name' => 'Jakarta Timur', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 31, 'name' => 'Jakarta Pusat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 31, 'name' => 'Jakarta Barat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 31, 'name' => 'Jakarta Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 32, 'name' => 'Bogor', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 32, 'name' => 'Sukabumi', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 32, 'name' => 'Cianjur', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 32, 'name' => 'Bandung', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 32, 'name' => 'Garut', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 32, 'name' => 'Tasikmalaya', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 32, 'name' => 'Ciamis', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 32, 'name' => 'Kuningan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 32, 'name' => 'Cirebon', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 32, 'name' => 'Majalengka', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 32, 'name' => 'Sumedang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 32, 'name' => 'Indramayu', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 32, 'name' => 'Subang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 32, 'name' => 'Purwakarta', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 32, 'name' => 'Karawang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 32, 'name' => 'Bekasi', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 32, 'name' => 'Bandung Barat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 32, 'name' => 'Pangandaran', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 32, 'name' => 'Bogor', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 32, 'name' => 'Sukabumi', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 32, 'name' => 'Bandung', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 32, 'name' => 'Cirebon', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 32, 'name' => 'Bekasi', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 32, 'name' => 'Depok', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 32, 'name' => 'Cimahi', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 32, 'name' => 'Tasikmalaya', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 32, 'name' => 'Banjar', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 33, 'name' => 'Cilacap', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 33, 'name' => 'Banyumas', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 33, 'name' => 'Purbalingga', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 33, 'name' => 'Banjarnegara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 33, 'name' => 'Kebumen', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 33, 'name' => 'Purworejo', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 33, 'name' => 'Wonosobo', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 33, 'name' => 'Magelang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 33, 'name' => 'Boyolali', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 33, 'name' => 'Klaten', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 33, 'name' => 'Sukoharjo', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 33, 'name' => 'Wonogiri', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 33, 'name' => 'Karanganyar', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 33, 'name' => 'Sragen', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 33, 'name' => 'Grobogan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 33, 'name' => 'Blora', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 33, 'name' => 'Rembang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 33, 'name' => 'Pati', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 33, 'name' => 'Kudus', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 33, 'name' => 'Jepara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 33, 'name' => 'Demak', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 33, 'name' => 'Semarang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 33, 'name' => 'Temanggung', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 33, 'name' => 'Kendal', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 33, 'name' => 'Batang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 33, 'name' => 'Pekalongan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 33, 'name' => 'Pemalang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 33, 'name' => 'Tegal', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 33, 'name' => 'Brebes', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 33, 'name' => 'Magelang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 33, 'name' => 'Surakarta', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 33, 'name' => 'Salatiga', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 33, 'name' => 'Semarang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 33, 'name' => 'Pekalongan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 33, 'name' => 'Tegal', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 34, 'name' => 'Kulon Progo', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 34, 'name' => 'Bantul', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 34, 'name' => 'Gunung Kidul', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 34, 'name' => 'Sleman', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 34, 'name' => 'Yogyakarta', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 35, 'name' => 'Pacitan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 35, 'name' => 'Ponorogo', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 35, 'name' => 'Trenggalek', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 35, 'name' => 'Tulungagung', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 35, 'name' => 'Blitar', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 35, 'name' => 'Kediri', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 35, 'name' => 'Malang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 35, 'name' => 'Lumajang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 35, 'name' => 'Jember', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 35, 'name' => 'Banyuwangi', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 35, 'name' => 'Bondowoso', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 35, 'name' => 'Situbondo', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 35, 'name' => 'Probolinggo', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 35, 'name' => 'Pasuruan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 35, 'name' => 'Sidoarjo', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 35, 'name' => 'Mojokerto', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 35, 'name' => 'Jombang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 35, 'name' => 'Nganjuk', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 35, 'name' => 'Madiun', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 35, 'name' => 'Magetan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 35, 'name' => 'Ngawi', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 35, 'name' => 'Bojonegoro', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 35, 'name' => 'Tuban', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 35, 'name' => 'Lamongan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 35, 'name' => 'Gresik', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 35, 'name' => 'Bangkalan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 35, 'name' => 'Sampang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 35, 'name' => 'Pamekasan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 35, 'name' => 'Sumenep', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 35, 'name' => 'Kediri', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 35, 'name' => 'Blitar', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 35, 'name' => 'Malang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 35, 'name' => 'Probolinggo', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 35, 'name' => 'Pasuruan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 35, 'name' => 'Mojokerto', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 35, 'name' => 'Madiun', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 35, 'name' => 'Surabaya', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 35, 'name' => 'Batu', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 36, 'name' => 'Pandeglang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 36, 'name' => 'Lebak', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 36, 'name' => 'Tangerang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 36, 'name' => 'Serang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 36, 'name' => 'Tangerang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 36, 'name' => 'Cilegon', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 36, 'name' => 'Serang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 36, 'name' => 'Tangerang Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 51, 'name' => 'Jembrana', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 51, 'name' => 'Tabanan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 51, 'name' => 'Badung', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 51, 'name' => 'Gianyar', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 51, 'name' => 'Klungkung', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 51, 'name' => 'Bangli', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 51, 'name' => 'Karang Asem', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 51, 'name' => 'Buleleng', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 51, 'name' => 'Denpasar', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 52, 'name' => 'Lombok Barat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 52, 'name' => 'Lombok Tengah', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 52, 'name' => 'Lombok Timur', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 52, 'name' => 'Sumbawa', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 52, 'name' => 'Dompu', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 52, 'name' => 'Bima', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 52, 'name' => 'Sumbawa Barat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 52, 'name' => 'Lombok Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 52, 'name' => 'Mataram', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 52, 'name' => 'Bima', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 53, 'name' => 'Sumba Barat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 53, 'name' => 'Sumba Timur', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 53, 'name' => 'Kupang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 53, 'name' => 'Timor Tengah Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 53, 'name' => 'Timor Tengah Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 53, 'name' => 'Belu', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 53, 'name' => 'Alor', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 53, 'name' => 'Lembata', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 53, 'name' => 'Flores Timur', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 53, 'name' => 'Sikka', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 53, 'name' => 'Ende', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 53, 'name' => 'Ngada', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 53, 'name' => 'Manggarai', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 53, 'name' => 'Rote Ndao', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 53, 'name' => 'Manggarai Barat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 53, 'name' => 'Sumba Tengah', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 53, 'name' => 'Sumba Barat Daya', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 53, 'name' => 'Nagekeo', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 53, 'name' => 'Manggarai Timur', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 53, 'name' => 'Sabu Raijua', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 53, 'name' => 'Malaka', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 53, 'name' => 'Kupang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 61, 'name' => 'Sambas', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 61, 'name' => 'Bengkayang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 61, 'name' => 'Landak', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 61, 'name' => 'Mempawah', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 61, 'name' => 'Sanggau', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 61, 'name' => 'Ketapang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 61, 'name' => 'Sintang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 61, 'name' => 'Kapuas Hulu', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 61, 'name' => 'Sekadau', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 61, 'name' => 'Melawi', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 61, 'name' => 'Kayong Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 61, 'name' => 'Kubu Raya', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 61, 'name' => 'Pontianak', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 61, 'name' => 'Singkawang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 62, 'name' => 'Kotawaringin Barat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 62, 'name' => 'Kotawaringin Timur', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 62, 'name' => 'Kapuas', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 62, 'name' => 'Barito Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 62, 'name' => 'Barito Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 62, 'name' => 'Sukamara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 62, 'name' => 'Lamandau', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 62, 'name' => 'Seruyan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 62, 'name' => 'Katingan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 62, 'name' => 'Pulang Pisau', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 62, 'name' => 'Gunung Mas', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 62, 'name' => 'Barito Timur', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 62, 'name' => 'Murung Raya', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 62, 'name' => 'Palangka Raya', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 63, 'name' => 'Tanah Laut', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 63, 'name' => 'Kota Baru', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 63, 'name' => 'Banjar', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 63, 'name' => 'Barito Kuala', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 63, 'name' => 'Tapin', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 63, 'name' => 'Hulu Sungai Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 63, 'name' => 'Hulu Sungai Tengah', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 63, 'name' => 'Hulu Sungai Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 63, 'name' => 'Tabalong', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 63, 'name' => 'Tanah Bumbu', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 63, 'name' => 'Balangan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 63, 'name' => 'Banjarmasin', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 63, 'name' => 'Banjar Baru', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 64, 'name' => 'Paser', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 64, 'name' => 'Kutai Barat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 64, 'name' => 'Kutai Kartanegara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 64, 'name' => 'Kutai Timur', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 64, 'name' => 'Berau', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 64, 'name' => 'Penajam Paser Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 64, 'name' => 'Mahakam Hulu', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 64, 'name' => 'Balikpapan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 64, 'name' => 'Samarinda', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 64, 'name' => 'Bontang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 65, 'name' => 'Malinau', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 65, 'name' => 'Bulungan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 65, 'name' => 'Tana Tidung', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 65, 'name' => 'Nunukan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 65, 'name' => 'Tarakan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 71, 'name' => 'Bolaang Mongondow', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 71, 'name' => 'Minahasa', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 71, 'name' => 'Kepulauan Sangihe', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 71, 'name' => 'Kepulauan Talaud', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 71, 'name' => 'Minahasa Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 71, 'name' => 'Minahasa Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 71, 'name' => 'Bolaang Mongondow Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 71, 'name' => 'Kepulauan Siau Tagulandang Biaro', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 71, 'name' => 'Minahasa Tenggara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 71, 'name' => 'Bolaang Mongondow Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 71, 'name' => 'Bolaang Mongondow Timur', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 71, 'name' => 'Manado', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 71, 'name' => 'Bitung', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 71, 'name' => 'Tomohon', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 71, 'name' => 'Kotamobagu', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 72, 'name' => 'Banggai Kepulauan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 72, 'name' => 'Banggai', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 72, 'name' => 'Morowali', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 72, 'name' => 'Poso', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 72, 'name' => 'Donggala', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 72, 'name' => 'Toli-toli', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 72, 'name' => 'Buol', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 72, 'name' => 'Parigi Moutong', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 72, 'name' => 'Tojo Una-una', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 72, 'name' => 'Sigi', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 72, 'name' => 'Banggai Laut', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 72, 'name' => 'Morowali Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 72, 'name' => 'Palu', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 73, 'name' => 'Kepulauan Selayar', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 73, 'name' => 'Bulukumba', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 73, 'name' => 'Bantaeng', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 73, 'name' => 'Jeneponto', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 73, 'name' => 'Takalar', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 73, 'name' => 'Gowa', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 73, 'name' => 'Sinjai', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 73, 'name' => 'Maros', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 73, 'name' => 'Pangkajene Dan Kepulauan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 73, 'name' => 'Barru', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 73, 'name' => 'Bone', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 73, 'name' => 'Soppeng', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 73, 'name' => 'Wajo', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 73, 'name' => 'Sidenreng Rappang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 73, 'name' => 'Pinrang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 73, 'name' => 'Enrekang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 73, 'name' => 'Luwu', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 73, 'name' => 'Tana Toraja', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 73, 'name' => 'Luwu Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 73, 'name' => 'Luwu Timur', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 73, 'name' => 'Toraja Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 73, 'name' => 'Makassar', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 73, 'name' => 'Parepare', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 73, 'name' => 'Palopo', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 74, 'name' => 'Buton', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 74, 'name' => 'Muna', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 74, 'name' => 'Konawe', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 74, 'name' => 'Kolaka', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 74, 'name' => 'Konawe Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 74, 'name' => 'Bombana', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 74, 'name' => 'Wakatobi', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 74, 'name' => 'Kolaka Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 74, 'name' => 'Buton Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 74, 'name' => 'Konawe Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 74, 'name' => 'Kolaka Timur', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 74, 'name' => 'Konawe Kepulauan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 74, 'name' => 'Muna Barat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 74, 'name' => 'Buton Tengah', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 74, 'name' => 'Buton Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 74, 'name' => 'Kendari', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 74, 'name' => 'Baubau', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 75, 'name' => 'Boalemo', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 75, 'name' => 'Gorontalo', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 75, 'name' => 'Pohuwato', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 75, 'name' => 'Bone Bolango', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 75, 'name' => 'Gorontalo Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 75, 'name' => 'Gorontalo', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 76, 'name' => 'Majene', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 76, 'name' => 'Polewali Mandar', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 76, 'name' => 'Mamasa', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 76, 'name' => 'Mamuju', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 76, 'name' => 'Mamuju Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 76, 'name' => 'Mamuju Tengah', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 81, 'name' => 'Maluku Tenggara Barat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 81, 'name' => 'Maluku Tenggara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 81, 'name' => 'Maluku Tengah', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 81, 'name' => 'Buru', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 81, 'name' => 'Kepulauan Aru', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 81, 'name' => 'Seram Bagian Barat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 81, 'name' => 'Seram Bagian Timur', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 81, 'name' => 'Maluku Barat Daya', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 81, 'name' => 'Buru Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 81, 'name' => 'Ambon', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 81, 'name' => 'Tual', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 82, 'name' => 'Halmahera Barat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 82, 'name' => 'Halmahera Tengah', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 82, 'name' => 'Kepulauan Sula', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 82, 'name' => 'Halmahera Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 82, 'name' => 'Halmahera Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 82, 'name' => 'Halmahera Timur', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 82, 'name' => 'Pulau Morotai', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 82, 'name' => 'Pulau Taliabu', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 82, 'name' => 'Ternate', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 82, 'name' => 'Tidore Kepulauan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 91, 'name' => 'Fakfak', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 91, 'name' => 'Kaimana', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 91, 'name' => 'Teluk Wondama', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 91, 'name' => 'Teluk Bintuni', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 91, 'name' => 'Manokwari', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 91, 'name' => 'Sorong Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 91, 'name' => 'Sorong', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 91, 'name' => 'Raja Ampat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 91, 'name' => 'Tambrauw', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 91, 'name' => 'Maybrat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 91, 'name' => 'Manokwari Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 91, 'name' => 'Pegunungan Arfak', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 91, 'name' => 'Sorong', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 94, 'name' => 'Merauke', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 94, 'name' => 'Jayawijaya', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 94, 'name' => 'Jayapura', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 94, 'name' => 'Nabire', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 94, 'name' => 'Kepulauan Yapen', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 94, 'name' => 'Biak Numfor', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 94, 'name' => 'Paniai', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 94, 'name' => 'Puncak Jaya', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 94, 'name' => 'Mimika', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 94, 'name' => 'Boven Digoel', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 94, 'name' => 'Mappi', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 94, 'name' => 'Asmat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 94, 'name' => 'Yahukimo', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 94, 'name' => 'Pegunungan Bintang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 94, 'name' => 'Tolikara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 94, 'name' => 'Sarmi', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 94, 'name' => 'Keerom', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 94, 'name' => 'Waropen', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 94, 'name' => 'Supiori', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 94, 'name' => 'Mamberamo Raya', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 94, 'name' => 'Nduga', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 94, 'name' => 'Lanny Jaya', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 94, 'name' => 'Mamberamo Tengah', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 94, 'name' => 'Yalimo', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 94, 'name' => 'Puncak', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 94, 'name' => 'Dogiyai', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 94, 'name' => 'Intan Jaya', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 94, 'name' => 'Deiyai', 'created_at' => now(), 'updated_at' => now()],
            ['id' => Uuid::generate()->string, 'province_id' => $dummyProvinceId, 'province_old_id' => 94, 'name' => 'Jayapura', 'created_at' => now(), 'updated_at' => now()]
        ]);
        DB::select('UPDATE master_cities SET province_id = (SELECT id FROM master_provinces WHERE old_id = province_old_id)');
        DB::select('ALTER TABLE master_provinces DROP COLUMN old_id');
        DB::select('ALTER TABLE master_cities DROP COLUMN province_old_id');
    }
}
